apiVersion: v1
kind: Secret
metadata:
  name: azure-csc-account
  namespace: monitoring
  labels:
    name: azure-csc-account
data:
  azure_sp_app_id: {{ "app_id" | b64encode }}
  azure_sp_secret: {{ "secret" | b64encode }}
  azure_sp_tenant_id: {{ "tenant_id" | b64encode }}